### ISSUE TITLE
html visualization is not compatible in databricks

### ISSUE THREAD

**Issue by vkocaman** [JohnSnowLabs/spark-nlp-display#1]
pandas.display.Html is not working in databricks. So, the workaround is displayHTML() <a databricks specific command>

see this for example >> https://github.com/JohnSnowLabs/spark-nlp-workshop/blob/master/tutorials/Certification_Trainings/Public/databricks_notebooks/3.SparkNLP_Pretrained_Models_v2.6.3.ipynb

```
wget -q https://raw.githubusercontent.com/JohnSnowLabs/spark-nlp-workshop/master/tutorials/Certification_Trainings/Public/utils/ner_highlighter.py
import sys
sys.path.append('/databricks/driver/')
sys.path.append('/databricks/driver/ner_highlighter.py')
import ner_highlighter
light_result_basic = light_pipeline.annotate(clinical_note)
displayHTML(ner_highlighter.token_highlighter(light_result_basic))
```

**Comment by HashamUlHaq** [comment]
Fixed by adding a new parameter "return_html" which returns raw html - this can enable users to visualise in practically any environment outside jupyter.

**Comment by vkocaman** [comment]
good job ! thank you
