### ISSUE TITLE
License for dependency_conllu

### ISSUE THREAD

**Issue by gourav-sg** [JohnSnowLabs/spark-nlp-display#6]
Hi,
for using the model dependency_conllu what is the kind of license do we need? 

Regards,
Gourav

**Comment by HashamUlHaq** [comment]
Hi @gourav-sg you don't need license to use dependency_conllu model as it's open source. To check out how you can use, please visit Spark NLP's models hub (https://nlp.johnsnowlabs.com/models). Here is the model you want https://nlp.johnsnowlabs.com/2021/03/27/dependency_conllu_en.html.

Also, you can ask model related questions on the main github repo: https://github.com/JohnSnowLabs/spark-nlp

**Comment by gourav-sg** [comment]
:) Thanks a ton @HashamUlHaq
